nameOverride: "devspaces"
fullnameOverride: ""

namespace: ""

devEnvironments:
  startTimeoutSeconds: 300
  secondsOfRunBeforeIdling: 600
  maxNumberOfWorkspacesPerUser: 2
  defaultEditor: che-incubator/che-code/latest

gitlab:
  host: ""

oidc:
  identityProviderURL: ""
  oAuthClientName: ""
  oAuthSecret: ""

argocd:
  enabled: true
  instance:
    syncwave: "0"
