kind: Deployment
apiVersion: apps/v1
metadata:
  name: insurances-v1
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: insurances
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: insurances
        version: v1
    spec:
      containers:
        - name: insurances
          image: quay.io/kiali/demo_travels_insurances:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
          env:
            - name: CURRENT_SERVICE
              value: "insurances"
            - name: CURRENT_VERSION
              value: "v1"
            - name: LISTEN_ADDRESS
              value: ":8000"
            - name: DISCOUNTS_SERVICE
              value: "http://discounts.travel-agency:8000"
            - name: MYSQL_SERVICE
              value: "mysqldb.travel-agency:3306"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: rootpasswd
            - name: MYSQL_DATABASE
              value: "test"