postgres:
  authSecret:
    name: sonataflow-psql-postgresql
    passwordKey: database-password
    userKey: database-user
  database: sonataflow
  service: sonataflow-psql-postgresql

backstage:
  namespace: backstage
  operator:
    enabled: false
  backend:
    token:
    url:

openshift:
  token:
  url:

gitlab:
  token:
  url:

argocd:
  enabled: true
  orchestrator:
    syncwave: "0"

