postgres:
  authSecret:
    name: backstage-postgresql-svcbind-postgres
    passwordKey: password
    userKey: username
  database: sonataflow
  service: backstage-postgresql

backstage:
  namespace: backstage
  operator:
    enabled: false
  backend:
    token:
    url:

openshift:
  token:
  url:

gitlab:
  token:
  url:

argocd:
  enabled: true
  orchestrator:
    syncwave: "0"

