nameOverride: "devspaces"
fullnameOverride: ""

namespace: ""

devspaces:
  subscription:
    channel: stable
    installPlanApproval: Automatic
    name: devspacesoperator
    source: devspaces-catalogsource
    sourceNamespace: openshift-marketplace

argocd:
  enabled: true
  operatorgroup:
    syncwave: "-3"
  operator:
    syncwave: "-2"
