kind: Service
apiVersion: v1
metadata:
  name: travels-demo-ui
  namespace: blue-portal
  labels:
    app: travels-demo-ui
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: travels-demo-ui
